### ISSUE TITLE
New Maintainer needed

### ISSUE THREAD

**Issue by rgcjonas** [rgcjonas/gnome-shell-extension-appindicator#56]
I don't have enough time anymore to continue maintaining the extension with the current feature set.

What is the state of the project? What will be expected of my successor?
- The code is fairly mature, and working well. There isn't any major development needed. However, there still are some bugs lurking within, and the low-hanging fruit has been picked already.
- Some home-grown hacks are used throughout the code base, and this might not scale in the long run.
- Sadly, a number of GNOME bugs need to be worked around.
- The AppIndicator/KStatusNotifierItem protocol is only barely specified, and the spec that floated around in the net is outdated and wrong. Your best bet is to learn from existing implementations, and test with existing indicators.
- Gnome 3.16 needs to be supported as soon as possible, and the message tray redesign might have broken some things.

In order to be successful at developing and maintaining this extension, you probably should have some experience in writing extensions for the Gnome Shell, or gnome-related software development in general.

Are you interested? Write a comment explaining why you're suited best for the task.

**Comment by axfelix** [comment]
TopIcons Plus is in very good shape for the time being, if anyone wants to use it; this extension was far superior to the original topicons, and there are still some elements of it that I like better than Topicons Plus, but until this is better-maintained and stable, that's a good alternative.

https://extensions.gnome.org/extension/1031/topicons/

It also supports Dropbox, which this extension never did due to Qt5 issues.

**Comment by jhasse** [comment]
I would be interested in taking over maintaining this extension :) I don't have much experience in writing GNOME Shell extension though.

**Comment by dralley** [comment]
@rgcjonas ^^^

**Comment by rgcjonas** [comment]
@jhasse I just enabled push access to this repository for you (hopefully it worked - otherwise let me know).

Congrats for being the new maintainer!

I'll figure out how to transfer the ownership on extensions.gnome.org.

**Comment by jhasse** [comment]
Yes it worked :) Thank you!

**Comment by dralley** [comment]
@rgcjonas While you try to transfer ownership, could you please push the latest version of the extension to extensions.gnome.org?  As it stands the plugin can't be installed as-is from the extension site on Fedora 24 or 25 because the latest version available does not have an up to date metadata.json

**Comment by jhasse** [comment]
Latest version should now be available at extensions.gnome.org :)
